#ifndef AVALON_UTILS_PLATFORM_H
#define AVALON_UTILS_PLATFORM_H

#include <string>

#define AVALON_PLATFORM_FLAVOR_AMAZON 1
#define AVALON_PLATFORM_FLAVOR_GOOGLE 2
#define AVALON_PLATFORM_FLAVOR_SAMSUNG 3

#ifdef __APPLE__
    #include "TargetConditionals.h"
    #if TARGET_IPHONE_SIMULATOR
        #define AVALON_PLATFORM_IS_IOS 1
    #elif TARGET_OS_IPHONE
        #define AVALON_PLATFORM_IS_IOS 1
    #elif TARGET_OS_MAC
        #define AVALON_PLATFORM_IS_MAC 1
    #else
        // Unsupported platform
    #endif
#elif __ANDROID__
    #define AVALON_PLATFORM_IS_ANDROID 1
#endif //__APPLE__


#ifdef AVALON_PLATFORM_IS_ANDROID
    #ifndef AVALON_PLATFORM_FLAVOR
        #error "You have to define AVALON_PLATFORM_FLAVOR first"
    #elif (AVALON_PLATFORM_FLAVOR != AVALON_PLATFORM_FLAVOR_AMAZON) \
       && (AVALON_PLATFORM_FLAVOR != AVALON_PLATFORM_FLAVOR_GOOGLE) \
       && (AVALON_PLATFORM_FLAVOR != AVALON_PLATFORM_FLAVOR_SAMSUNG)
        #error "Invalid AVALON_PLATFORM_FLAVOR defined"
    #endif
#else
    #define AVALON_PLATFORM_FLAVOR 0
#endif

#define AVALON_PLATFORM_IS_ANDROID_AMAZON  (AVALON_PLATFORM_IS_ANDROID && (AVALON_PLATFORM_FLAVOR == AVALON_PLATFORM_FLAVOR_AMAZON))
#define AVALON_PLATFORM_IS_ANDROID_GOOGLE  (AVALON_PLATFORM_IS_ANDROID && (AVALON_PLATFORM_FLAVOR == AVALON_PLATFORM_FLAVOR_GOOGLE))
#define AVALON_PLATFORM_IS_ANDROID_SAMSUNG (AVALON_PLATFORM_IS_ANDROID && (AVALON_PLATFORM_FLAVOR == AVALON_PLATFORM_FLAVOR_SAMSUNG))

#endif /* AVALON_UTILS_PLATFORM_H */
